取消大文件传输任务

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,17 +13,17 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v4
         with:
-          lfs: true
+          lfs: false # 现在禁止自动拉取 LFS 文件，大文件手动上传到服务器，避免 GitHub Action 因为大文件导致的超时问题
 
-      - name: Pull And Verify LFS Zip Files
-        run: |
-          git lfs pull --include="public/resources/Echo-Mate/nand_buildroot_img_260329.zip,public/resources/Echo-Mate/sd_buildroot_img_260329.zip"
-          for f in public/resources/Echo-Mate/nand_buildroot_img_260329.zip public/resources/Echo-Mate/sd_buildroot_img_260329.zip; do
-            if grep -aq "version https://git-lfs.github.com/spec/v1" "$f"; then
-              echo "ERROR: $f is still an LFS pointer, not a real zip file"
-              exit 1
-            fi
-          done
+      # - name: Pull And Verify LFS Zip Files
+      #   run: |
+      #     git lfs pull --include="public/resources/Echo-Mate/nand_buildroot_img_260329.zip,public/resources/Echo-Mate/sd_buildroot_img_260329.zip"
+      #     for f in public/resources/Echo-Mate/nand_buildroot_img_260329.zip public/resources/Echo-Mate/sd_buildroot_img_260329.zip; do
+      #       if grep -aq "version https://git-lfs.github.com/spec/v1" "$f"; then
+      #         echo "ERROR: $f is still an LFS pointer, not a real zip file"
+      #         exit 1
+      #       fi
+      #     done
 
       - name: Sync Selected Files to Server
         uses: easingthemes/ssh-deploy@main
